### ISSUE TITLE
当使用高德的时候，提示找不到相关的Class

### ISSUE THREAD

**Issue by OranTing** [jhabc1314/jackdou-chinamap#1]
config里设置了。

    'default' => 'amap',

提示找不到相关的Class

<img width="1255" alt="xnip2018-09-25_00-24-53" src="https://user-images.githubusercontent.com/13476576/45964870-84f3e980-c059-11e8-9752-3b7dd65ca675.png">

**Comment by jhabc1314** [comment]
抱歉，类名大小写书写错误，已修复～

因为工作原因，项目暂时搁置了。。。
