### ISSUE TITLE
916 Target class [Jackdou\Chinamap\Maps\QqMap] does not exist

### ISSUE THREAD

**Issue by LeesinYii** [jhabc1314/jackdou-chinamap#3]
大小写写错了，导致在 linux 服务器找不到该类，这块我看没人反馈过
`$className = 'Jackdou\Chinamap\Maps\\' . ucfirst($item) . 'Map';`
其实文件名都是小写 map.php

**Comment by jhabc1314** [comment]
hi，感谢指出问题😀，现在已经修复，可以更新一下版本💓。

这两天我看看要不要升级一下，很久没有维护了😂
